name: ShareIt API Tests

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v2

    uses: yandex-praktikum/java-shareit/.github/workflows/api-tests.yml@ci